name: Publish a package

on:
    release:
        types: [released]

jobs:
    publish-gh:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
                  scope: "@${{github.repository_owner}}"
            - run: npm install
            - run: |
                  npm config set registry=https://npm.pkg.github.com
                  npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.PAT}}

    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
                  scope: "@${{github.repository_owner}}"
            - run: npm install
              env:
                  NODE_AUTH_TOKEN: ${{github.token}}
            - run: |
                  npm config set registry=https://registry.npmjs.org
                  npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
